export type InterfaceIconType =
  'add-circle' | 
  'add' |
  'alarm' |
  'alert' |
  'alert-circle' |
  'apps' |
  'arrow-redo' |
  'bookmarks' |
  'cellular' |
  'checkbox' |
  'chevron-forward' |
  'chevron-back' |
  'close' |
  'download' |
  'duplicate' |
  'ellipsis-horizontal' |
  'enter' |
  'expand' |
  'eye' |
  'eye-off' |
  'filter' |
  'funnel' |
  'grid' |
  'information-circle' |
  'layers' |
  'link' |
  'list' |
  'location' |
  'menu' |
  'mic' |
  'navigate' |
  'notifications' |
  'notifications-off' |
  'options' |
  'person' |
  'person-add' |
  'play' |
  'power' |
  'push' |
  'reload' |
  'search' |
  'share-social' |
  'settings' |
  'trash' |
  'trending-up' |
  'trending-down';